name: Workflow with environment Secrets
on: workflow_dispatch
jobs:
  greeting_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Say Hello Serhat it's Monday"
        run: echo "${{ secrets.Greeting }} ${{ secrets.First_Name }}. Today is ${{ secrets.DAY_OF_WEEK }}!"
